# Generated by Django 4.1.5 on 2023-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('discription', models.CharField(max_length=150)),
            ],
        ),
    ]
