# Generated by Django 4.1.5 on 2023-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_category',
            name='image',
            field=models.FileField(default='', upload_to='./car_category/'),
        ),
    ]
