# Generated by Django 4.1.5 on 2023-05-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0004_car_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_category',
            name='discription',
            field=models.CharField(max_length=550),
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('prize', models.BigIntegerField()),
                ('discription', models.CharField(max_length=500)),
                ('image', models.FileField(default='', upload_to='./car_image/')),
                ('person', models.BigIntegerField()),
                ('music', models.CharField(max_length=50)),
                ('ac', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.car_category')),
            ],
        ),
    ]
