# Generated by Django 4.1.5 on 2023-05-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_car_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
