# Generated by Django 4.1.5 on 2023-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0008_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='prize',
            field=models.CharField(max_length=50),
        ),
    ]
