# Generated by Django 4.1.5 on 2023-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0010_alter_car_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=200)),
                ('image', models.FileField(default='', upload_to='./slide')),
            ],
        ),
    ]
