# Generated by Django 4.1.5 on 2023-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('pick_up', models.CharField(max_length=50)),
                ('drop', models.CharField(max_length=50)),
                ('pickup_date', models.CharField(max_length=50)),
                ('drop_date', models.CharField(max_length=50)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('request', models.CharField(max_length=500)),
                ('payment', models.CharField(max_length=50)),
            ],
        ),
    ]
