# Generated by Django 4.1.5 on 2023-05-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0011_slide'),
        ('frontend', '0004_rename_drop_date_booking_detail_drop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_detail',
            name='car_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='admin_side.car'),
            preserve_default=False,
        ),
    ]
