# Generated by Django 4.1.5 on 2023-05-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_booking_detail_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_detail',
            name='car_name',
            field=models.CharField(max_length=50),
        ),
    ]
