# Generated by Django 4.1.5 on 2023-05-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0011_slide'),
        ('frontend', '0006_alter_booking_detail_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_detail',
            name='car_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.car'),
        ),
    ]
