# Generated by Django 4.1.5 on 2023-05-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_booking_detail_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_detail',
            old_name='car_name',
            new_name='car_id',
        ),
    ]
