# Generated by Django 4.1.5 on 2023-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_rename_car_name_booking_detail_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_detail',
            name='car_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
