# Generated by Django 4.1.5 on 2023-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profession',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
