# Generated by Django 4.1.5 on 2023-07-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_signup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profession',
        ),
    ]
